// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfreigfygqxnwaafgwvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcmVpZ2Z5Z3F4bndhYWZnd3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Njc1OTQsImV4cCI6MjA3MzE0MzU5NH0.YwrYcYFEh903zhF6G-rhf5E37uq9ZSKPsnV75_igJp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});